/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BackupIndexRouteImport } from './routes/backup/index'
import { Route as BackupJobsRouteImport } from './routes/backup/jobs'
import { Route as JobsIndexRouteImport } from './routes/jobs/index'
import { Route as RestoreIndexRouteImport } from './routes/restore/index'
import { Route as RestoreJobsRouteImport } from './routes/restore/jobs'

const ConfigIndexLazyRouteImport = createFileRoute('/config/')()
const ConfigImportLazyRouteImport = createFileRoute('/config/import')()
const ConfigNotifiersLazyRouteImport = createFileRoute('/config/notifiers')()
const ConfigRestoreTargetsLazyRouteImport = createFileRoute(
  '/config/restore-targets',
)()
const ConfigStoragesLazyRouteImport = createFileRoute('/config/storages')()
const ConfigTargetsLazyRouteImport = createFileRoute('/config/targets')()
const JobsIdLazyRouteImport = createFileRoute('/jobs/$id')()

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BackupIndexRoute = BackupIndexRouteImport.update({
  id: '/backup/',
  path: '/backup/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/backup/index.lazy').then((d) => d.Route))
const BackupJobsRoute = BackupJobsRouteImport.update({
  id: '/backup/jobs',
  path: '/backup/jobs',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/backup/jobs.lazy').then((d) => d.Route))
const ConfigIndexLazyRoute = ConfigIndexLazyRouteImport.update({
  id: '/config/',
  path: '/config/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/config/index.lazy').then((d) => d.Route))
const ConfigImportLazyRoute = ConfigImportLazyRouteImport.update({
  id: '/config/import',
  path: '/config/import',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/config/import.lazy').then((d) => d.Route))
const ConfigNotifiersLazyRoute = ConfigNotifiersLazyRouteImport.update({
  id: '/config/notifiers',
  path: '/config/notifiers',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/config/notifiers.lazy').then((d) => d.Route),
)
const ConfigRestoreTargetsLazyRoute =
  ConfigRestoreTargetsLazyRouteImport.update({
    id: '/config/restore-targets',
    path: '/config/restore-targets',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/config/restore-targets.lazy').then((d) => d.Route),
  )
const ConfigStoragesLazyRoute = ConfigStoragesLazyRouteImport.update({
  id: '/config/storages',
  path: '/config/storages',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/config/storages.lazy').then((d) => d.Route),
)
const ConfigTargetsLazyRoute = ConfigTargetsLazyRouteImport.update({
  id: '/config/targets',
  path: '/config/targets',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/config/targets.lazy').then((d) => d.Route),
)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/jobs/index.lazy').then((d) => d.Route))
const JobsIdLazyRoute = JobsIdLazyRouteImport.update({
  id: '/jobs/$id',
  path: '/jobs/$id',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/jobs/$id.lazy').then((d) => d.Route))
const RestoreIndexRoute = RestoreIndexRouteImport.update({
  id: '/restore/',
  path: '/restore/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/restore/index.lazy').then((d) => d.Route))
const RestoreJobsRoute = RestoreJobsRouteImport.update({
  id: '/restore/jobs',
  path: '/restore/jobs',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/restore/jobs.lazy').then((d) => d.Route))

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/backup/jobs': typeof BackupJobsRoute
  '/restore/jobs': typeof RestoreJobsRoute
  '/config/import': typeof ConfigImportLazyRoute
  '/config/notifiers': typeof ConfigNotifiersLazyRoute
  '/config/restore-targets': typeof ConfigRestoreTargetsLazyRoute
  '/config/storages': typeof ConfigStoragesLazyRoute
  '/config/targets': typeof ConfigTargetsLazyRoute
  '/jobs/$id': typeof JobsIdLazyRoute
  '/backup/': typeof BackupIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/restore/': typeof RestoreIndexRoute
  '/config/': typeof ConfigIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/backup/jobs': typeof BackupJobsRoute
  '/restore/jobs': typeof RestoreJobsRoute
  '/config/import': typeof ConfigImportLazyRoute
  '/config/notifiers': typeof ConfigNotifiersLazyRoute
  '/config/restore-targets': typeof ConfigRestoreTargetsLazyRoute
  '/config/storages': typeof ConfigStoragesLazyRoute
  '/config/targets': typeof ConfigTargetsLazyRoute
  '/jobs/$id': typeof JobsIdLazyRoute
  '/backup': typeof BackupIndexRoute
  '/jobs': typeof JobsIndexRoute
  '/restore': typeof RestoreIndexRoute
  '/config': typeof ConfigIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/backup/jobs': typeof BackupJobsRoute
  '/restore/jobs': typeof RestoreJobsRoute
  '/config/import': typeof ConfigImportLazyRoute
  '/config/notifiers': typeof ConfigNotifiersLazyRoute
  '/config/restore-targets': typeof ConfigRestoreTargetsLazyRoute
  '/config/storages': typeof ConfigStoragesLazyRoute
  '/config/targets': typeof ConfigTargetsLazyRoute
  '/jobs/$id': typeof JobsIdLazyRoute
  '/backup/': typeof BackupIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/restore/': typeof RestoreIndexRoute
  '/config/': typeof ConfigIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/backup/jobs'
    | '/restore/jobs'
    | '/config/import'
    | '/config/notifiers'
    | '/config/restore-targets'
    | '/config/storages'
    | '/config/targets'
    | '/jobs/$id'
    | '/backup/'
    | '/jobs/'
    | '/restore/'
    | '/config/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/backup/jobs'
    | '/restore/jobs'
    | '/config/import'
    | '/config/notifiers'
    | '/config/restore-targets'
    | '/config/storages'
    | '/config/targets'
    | '/jobs/$id'
    | '/backup'
    | '/jobs'
    | '/restore'
    | '/config'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/backup/jobs'
    | '/restore/jobs'
    | '/config/import'
    | '/config/notifiers'
    | '/config/restore-targets'
    | '/config/storages'
    | '/config/targets'
    | '/jobs/$id'
    | '/backup/'
    | '/jobs/'
    | '/restore/'
    | '/config/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  BackupJobsRoute: typeof BackupJobsRoute
  RestoreJobsRoute: typeof RestoreJobsRoute
  ConfigImportLazyRoute: typeof ConfigImportLazyRoute
  ConfigNotifiersLazyRoute: typeof ConfigNotifiersLazyRoute
  ConfigRestoreTargetsLazyRoute: typeof ConfigRestoreTargetsLazyRoute
  ConfigStoragesLazyRoute: typeof ConfigStoragesLazyRoute
  ConfigTargetsLazyRoute: typeof ConfigTargetsLazyRoute
  JobsIdLazyRoute: typeof JobsIdLazyRoute
  BackupIndexRoute: typeof BackupIndexRoute
  JobsIndexRoute: typeof JobsIndexRoute
  RestoreIndexRoute: typeof RestoreIndexRoute
  ConfigIndexLazyRoute: typeof ConfigIndexLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backup/': {
      id: '/backup/'
      path: '/backup'
      fullPath: '/backup/'
      preLoaderRoute: typeof BackupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backup/jobs': {
      id: '/backup/jobs'
      path: '/backup/jobs'
      fullPath: '/backup/jobs'
      preLoaderRoute: typeof BackupJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/': {
      id: '/config/'
      path: '/config'
      fullPath: '/config/'
      preLoaderRoute: typeof ConfigIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/import': {
      id: '/config/import'
      path: '/config/import'
      fullPath: '/config/import'
      preLoaderRoute: typeof ConfigImportLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/notifiers': {
      id: '/config/notifiers'
      path: '/config/notifiers'
      fullPath: '/config/notifiers'
      preLoaderRoute: typeof ConfigNotifiersLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/restore-targets': {
      id: '/config/restore-targets'
      path: '/config/restore-targets'
      fullPath: '/config/restore-targets'
      preLoaderRoute: typeof ConfigRestoreTargetsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/storages': {
      id: '/config/storages'
      path: '/config/storages'
      fullPath: '/config/storages'
      preLoaderRoute: typeof ConfigStoragesLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/targets': {
      id: '/config/targets'
      path: '/config/targets'
      fullPath: '/config/targets'
      preLoaderRoute: typeof ConfigTargetsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$id': {
      id: '/jobs/$id'
      path: '/jobs/$id'
      fullPath: '/jobs/$id'
      preLoaderRoute: typeof JobsIdLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restore/': {
      id: '/restore/'
      path: '/restore'
      fullPath: '/restore/'
      preLoaderRoute: typeof RestoreIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restore/jobs': {
      id: '/restore/jobs'
      path: '/restore/jobs'
      fullPath: '/restore/jobs'
      preLoaderRoute: typeof RestoreJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  BackupJobsRoute: BackupJobsRoute,
  RestoreJobsRoute: RestoreJobsRoute,
  ConfigImportLazyRoute: ConfigImportLazyRoute,
  ConfigNotifiersLazyRoute: ConfigNotifiersLazyRoute,
  ConfigRestoreTargetsLazyRoute: ConfigRestoreTargetsLazyRoute,
  ConfigStoragesLazyRoute: ConfigStoragesLazyRoute,
  ConfigTargetsLazyRoute: ConfigTargetsLazyRoute,
  JobsIdLazyRoute: JobsIdLazyRoute,
  BackupIndexRoute: BackupIndexRoute,
  JobsIndexRoute: JobsIndexRoute,
  RestoreIndexRoute: RestoreIndexRoute,
  ConfigIndexLazyRoute: ConfigIndexLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
