/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BackupRouteImport } from './routes/backup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RestoreRouteImport } from './routes/restore'
import { Route as BackupJobsRouteImport } from './routes/backup/jobs'
import { Route as ConfigIndexRouteImport } from './routes/config/index'
import { Route as ConfigImportRouteImport } from './routes/config/import'
import { Route as ConfigNotifiersRouteImport } from './routes/config/notifiers'
import { Route as ConfigRestoreTargetsRouteImport } from './routes/config/restore-targets'
import { Route as ConfigStoragesRouteImport } from './routes/config/storages'
import { Route as ConfigTargetsRouteImport } from './routes/config/targets'
import { Route as JobsIndexRouteImport } from './routes/jobs/index'
import { Route as JobsIdRouteImport } from './routes/jobs/$id'
import { Route as RestoreJobsRouteImport } from './routes/restore/jobs'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BackupRoute = BackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RestoreRoute = RestoreRouteImport.update({
  id: '/restore',
  path: '/restore',
  getParentRoute: () => rootRouteImport,
} as any)
const BackupJobsRoute = BackupJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => BackupRoute,
} as any)
const ConfigIndexRoute = ConfigIndexRouteImport.update({
  id: '/config/',
  path: '/config/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigImportRoute = ConfigImportRouteImport.update({
  id: '/config/import',
  path: '/config/import',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigNotifiersRoute = ConfigNotifiersRouteImport.update({
  id: '/config/notifiers',
  path: '/config/notifiers',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRestoreTargetsRoute = ConfigRestoreTargetsRouteImport.update({
  id: '/config/restore-targets',
  path: '/config/restore-targets',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigStoragesRoute = ConfigStoragesRouteImport.update({
  id: '/config/storages',
  path: '/config/storages',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigTargetsRoute = ConfigTargetsRouteImport.update({
  id: '/config/targets',
  path: '/config/targets',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIdRoute = JobsIdRouteImport.update({
  id: '/jobs/$id',
  path: '/jobs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RestoreJobsRoute = RestoreJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => RestoreRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/backup': typeof BackupRouteWithChildren
  '/login': typeof LoginRoute
  '/restore': typeof RestoreRouteWithChildren
  '/backup/jobs': typeof BackupJobsRoute
  '/config/import': typeof ConfigImportRoute
  '/config/notifiers': typeof ConfigNotifiersRoute
  '/config/restore-targets': typeof ConfigRestoreTargetsRoute
  '/config/storages': typeof ConfigStoragesRoute
  '/config/targets': typeof ConfigTargetsRoute
  '/jobs/$id': typeof JobsIdRoute
  '/restore/jobs': typeof RestoreJobsRoute
  '/config/': typeof ConfigIndexRoute
  '/jobs/': typeof JobsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/backup': typeof BackupRouteWithChildren
  '/login': typeof LoginRoute
  '/restore': typeof RestoreRouteWithChildren
  '/backup/jobs': typeof BackupJobsRoute
  '/config/import': typeof ConfigImportRoute
  '/config/notifiers': typeof ConfigNotifiersRoute
  '/config/restore-targets': typeof ConfigRestoreTargetsRoute
  '/config/storages': typeof ConfigStoragesRoute
  '/config/targets': typeof ConfigTargetsRoute
  '/jobs/$id': typeof JobsIdRoute
  '/restore/jobs': typeof RestoreJobsRoute
  '/config': typeof ConfigIndexRoute
  '/jobs': typeof JobsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/backup': typeof BackupRouteWithChildren
  '/login': typeof LoginRoute
  '/restore': typeof RestoreRouteWithChildren
  '/backup/jobs': typeof BackupJobsRoute
  '/config/import': typeof ConfigImportRoute
  '/config/notifiers': typeof ConfigNotifiersRoute
  '/config/restore-targets': typeof ConfigRestoreTargetsRoute
  '/config/storages': typeof ConfigStoragesRoute
  '/config/targets': typeof ConfigTargetsRoute
  '/jobs/$id': typeof JobsIdRoute
  '/restore/jobs': typeof RestoreJobsRoute
  '/config/': typeof ConfigIndexRoute
  '/jobs/': typeof JobsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/backup'
    | '/login'
    | '/restore'
    | '/backup/jobs'
    | '/config/import'
    | '/config/notifiers'
    | '/config/restore-targets'
    | '/config/storages'
    | '/config/targets'
    | '/jobs/$id'
    | '/restore/jobs'
    | '/config/'
    | '/jobs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/backup'
    | '/login'
    | '/restore'
    | '/backup/jobs'
    | '/config/import'
    | '/config/notifiers'
    | '/config/restore-targets'
    | '/config/storages'
    | '/config/targets'
    | '/jobs/$id'
    | '/restore/jobs'
    | '/config'
    | '/jobs'
  id:
    | '__root__'
    | '/'
    | '/backup'
    | '/login'
    | '/restore'
    | '/backup/jobs'
    | '/config/import'
    | '/config/notifiers'
    | '/config/restore-targets'
    | '/config/storages'
    | '/config/targets'
    | '/jobs/$id'
    | '/restore/jobs'
    | '/config/'
    | '/jobs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BackupRoute: typeof BackupRouteWithChildren
  LoginRoute: typeof LoginRoute
  RestoreRoute: typeof RestoreRouteWithChildren
  ConfigImportRoute: typeof ConfigImportRoute
  ConfigNotifiersRoute: typeof ConfigNotifiersRoute
  ConfigRestoreTargetsRoute: typeof ConfigRestoreTargetsRoute
  ConfigStoragesRoute: typeof ConfigStoragesRoute
  ConfigTargetsRoute: typeof ConfigTargetsRoute
  JobsIdRoute: typeof JobsIdRoute
  ConfigIndexRoute: typeof ConfigIndexRoute
  JobsIndexRoute: typeof JobsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backup': {
      id: '/backup'
      path: '/backup'
      fullPath: '/backup'
      preLoaderRoute: typeof BackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restore': {
      id: '/restore'
      path: '/restore'
      fullPath: '/restore'
      preLoaderRoute: typeof RestoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backup/jobs': {
      id: '/backup/jobs'
      path: '/jobs'
      fullPath: '/backup/jobs'
      preLoaderRoute: typeof BackupJobsRouteImport
      parentRoute: typeof BackupRoute
    }
    '/config/': {
      id: '/config/'
      path: '/config'
      fullPath: '/config/'
      preLoaderRoute: typeof ConfigIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/import': {
      id: '/config/import'
      path: '/config/import'
      fullPath: '/config/import'
      preLoaderRoute: typeof ConfigImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/notifiers': {
      id: '/config/notifiers'
      path: '/config/notifiers'
      fullPath: '/config/notifiers'
      preLoaderRoute: typeof ConfigNotifiersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/restore-targets': {
      id: '/config/restore-targets'
      path: '/config/restore-targets'
      fullPath: '/config/restore-targets'
      preLoaderRoute: typeof ConfigRestoreTargetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/storages': {
      id: '/config/storages'
      path: '/config/storages'
      fullPath: '/config/storages'
      preLoaderRoute: typeof ConfigStoragesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/targets': {
      id: '/config/targets'
      path: '/config/targets'
      fullPath: '/config/targets'
      preLoaderRoute: typeof ConfigTargetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$id': {
      id: '/jobs/$id'
      path: '/jobs/$id'
      fullPath: '/jobs/$id'
      preLoaderRoute: typeof JobsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restore/jobs': {
      id: '/restore/jobs'
      path: '/jobs'
      fullPath: '/restore/jobs'
      preLoaderRoute: typeof RestoreJobsRouteImport
      parentRoute: typeof RestoreRoute
    }
  }
}

interface BackupRouteChildren {
  BackupJobsRoute: typeof BackupJobsRoute
}

const BackupRouteChildren: BackupRouteChildren = {
  BackupJobsRoute: BackupJobsRoute,
}

const BackupRouteWithChildren =
  BackupRoute._addFileChildren(BackupRouteChildren)

interface RestoreRouteChildren {
  RestoreJobsRoute: typeof RestoreJobsRoute
}

const RestoreRouteChildren: RestoreRouteChildren = {
  RestoreJobsRoute: RestoreJobsRoute,
}

const RestoreRouteWithChildren =
  RestoreRoute._addFileChildren(RestoreRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BackupRoute: BackupRouteWithChildren,
  LoginRoute: LoginRoute,
  RestoreRoute: RestoreRouteWithChildren,
  ConfigImportRoute: ConfigImportRoute,
  ConfigNotifiersRoute: ConfigNotifiersRoute,
  ConfigRestoreTargetsRoute: ConfigRestoreTargetsRoute,
  ConfigStoragesRoute: ConfigStoragesRoute,
  ConfigTargetsRoute: ConfigTargetsRoute,
  JobsIdRoute: JobsIdRoute,
  ConfigIndexRoute: ConfigIndexRoute,
  JobsIndexRoute: JobsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
