/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RestoreRouteImport } from './routes/restore'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BackupRouteImport } from './routes/backup'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RestoreJobsRouteImport } from './routes/restore/jobs'
import { Route as JobsIdRouteImport } from './routes/jobs/$id'
import { Route as BackupJobsRouteImport } from './routes/backup/jobs'

const RestoreRoute = RestoreRouteImport.update({
  id: '/restore',
  path: '/restore',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BackupRoute = BackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RestoreJobsRoute = RestoreJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => RestoreRoute,
} as any)
const JobsIdRoute = JobsIdRouteImport.update({
  id: '/jobs/$id',
  path: '/jobs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BackupJobsRoute = BackupJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => BackupRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/backup': typeof BackupRouteWithChildren
  '/login': typeof LoginRoute
  '/restore': typeof RestoreRouteWithChildren
  '/backup/jobs': typeof BackupJobsRoute
  '/jobs/$id': typeof JobsIdRoute
  '/restore/jobs': typeof RestoreJobsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/backup': typeof BackupRouteWithChildren
  '/login': typeof LoginRoute
  '/restore': typeof RestoreRouteWithChildren
  '/backup/jobs': typeof BackupJobsRoute
  '/jobs/$id': typeof JobsIdRoute
  '/restore/jobs': typeof RestoreJobsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/backup': typeof BackupRouteWithChildren
  '/login': typeof LoginRoute
  '/restore': typeof RestoreRouteWithChildren
  '/backup/jobs': typeof BackupJobsRoute
  '/jobs/$id': typeof JobsIdRoute
  '/restore/jobs': typeof RestoreJobsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/backup'
    | '/login'
    | '/restore'
    | '/backup/jobs'
    | '/jobs/$id'
    | '/restore/jobs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/backup'
    | '/login'
    | '/restore'
    | '/backup/jobs'
    | '/jobs/$id'
    | '/restore/jobs'
  id:
    | '__root__'
    | '/'
    | '/backup'
    | '/login'
    | '/restore'
    | '/backup/jobs'
    | '/jobs/$id'
    | '/restore/jobs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BackupRoute: typeof BackupRouteWithChildren
  LoginRoute: typeof LoginRoute
  RestoreRoute: typeof RestoreRouteWithChildren
  JobsIdRoute: typeof JobsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/restore': {
      id: '/restore'
      path: '/restore'
      fullPath: '/restore'
      preLoaderRoute: typeof RestoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backup': {
      id: '/backup'
      path: '/backup'
      fullPath: '/backup'
      preLoaderRoute: typeof BackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restore/jobs': {
      id: '/restore/jobs'
      path: '/jobs'
      fullPath: '/restore/jobs'
      preLoaderRoute: typeof RestoreJobsRouteImport
      parentRoute: typeof RestoreRoute
    }
    '/jobs/$id': {
      id: '/jobs/$id'
      path: '/jobs/$id'
      fullPath: '/jobs/$id'
      preLoaderRoute: typeof JobsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backup/jobs': {
      id: '/backup/jobs'
      path: '/jobs'
      fullPath: '/backup/jobs'
      preLoaderRoute: typeof BackupJobsRouteImport
      parentRoute: typeof BackupRoute
    }
  }
}

interface BackupRouteChildren {
  BackupJobsRoute: typeof BackupJobsRoute
}

const BackupRouteChildren: BackupRouteChildren = {
  BackupJobsRoute: BackupJobsRoute,
}

const BackupRouteWithChildren =
  BackupRoute._addFileChildren(BackupRouteChildren)

interface RestoreRouteChildren {
  RestoreJobsRoute: typeof RestoreJobsRoute
}

const RestoreRouteChildren: RestoreRouteChildren = {
  RestoreJobsRoute: RestoreJobsRoute,
}

const RestoreRouteWithChildren =
  RestoreRoute._addFileChildren(RestoreRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BackupRoute: BackupRouteWithChildren,
  LoginRoute: LoginRoute,
  RestoreRoute: RestoreRouteWithChildren,
  JobsIdRoute: JobsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
